# Generated by Django 5.1.3 on 2025-01-21 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_nb_reponses_qcm_nb_tentatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
