services:
  auto_qcm_python:
    container_name: auto_qcm_python
    image: piorigin/auto_qcm_python-prod:1.0.0
    build:
      context: ../
      dockerfile: Dockerfile
      target: ${env}
    depends_on:
      - auto_qcm_db
    env_file:
      - .env
    volumes:
      - ../auto_qcm/log/:/app/log/
    ports:
      - "80:8000"

  auto_qcm_db:
    container_name: auto_qcm_db
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
