name: Auto US

on:
  workflow_dispatch:
      inputs:
        issue_number:
          description: 'ID de l issue à traiter'
          required: true
          type: number
  push:
    branches: [auto-US-OMG]
  issues:
    types: [opened, edited, reopened]


jobs:
  auto_us:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd .github/workflows/auto_us
        pip install -r requirements.txt

    # Si c'est un workflow_dispatch, on récupère l'issue_number et on récupère l'issue
    - name: Get issue
      if: github.event_name == 'workflow_dispatch'
      run: |
        ISSUE_NUMBER=${{ github.event.inputs.issue_number }}
        RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                         -H "Accept: application/vnd.github.v3+json" \
                         https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER)

        ISSUE_TITLE=$(echo "$RESPONSE" | jq -r '.title')
        ISSUE_BODY=$(echo "$RESPONSE" | jq -r '.body')

        echo "Issue Number: $ISSUE_NUMBER"
        echo "Issue Title: $ISSUE_TITLE"
        echo "Issue Body: $ISSUE_BODY"

    # Si c'est un issue, on récupère l'issue
    - name: Get issue
      if: github.event_name == 'issues'
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        ISSUE_TITLE=${{ github.event.issue.title }}
        ISSUE_BODY=${{ github.event.issue.body }}

        echo "Issue Number: $ISSUE_NUMBER"
        echo "Issue Title: $ISSUE_TITLE"
        echo "Issue Body: $ISSUE_BODY"
