name: Docker Compose Release CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
  release:
    types: [published]

jobs:
  test:
    uses: enzofrnt/AUTO-QCM/.github/workflows/django.yml@main
    with:
      branch: ${{ github.ref_name }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    strategy:
      max-parallel: 2
      matrix:
        environment: [dev, prod]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set Docker image tag
      id: set-tag
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
        elif [ "${{ github.event_name }}" == "release" ]; then
          echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
        else
          echo "No valid tag found"
          exit 1
        fi

    - name: Build and push Docker images using Buildx
      run: |
        export env=${{ matrix.environment }}
        docker buildx create --use
        docker buildx build --push \
          --platform linux/amd64,linux/arm64 \
          --target $env \
          -t piorigin/auto_qcm_python-${{ matrix.environment }}:${{ env.tag }} .
